### ISSUE TITLE
Can not compile, I am begginer !!!

### ISSUE THREAD

**Issue by Formingus** [SensorsIot/Definitive-Guide-to-IR#11]
In file included from C:\Users\Formingus\Documents\Arduino\libraries\IRremoteESP8266\src/IRac.h:15:0,
                 from C:\Users\Formingus\AppData\Local\Temp\.arduinoIDE-unsaved2023916-5488-1m904gi.q7jqf\IRrecvDumpV2\IRrecvDumpV2.ino:33:
C:\Users\Formingus\Documents\Arduino\libraries\IRremoteESP8266\src/ir_Argo.h:14:10: fatal error: set: No such file or directory
 #include <set>
          ^~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by SensorsIot** [comment]
Did you install the IRremoteESP8266 library?

**Comment by Formingus** [comment]
Yes i did, From Tools, Manage Libraries 
I try with older versions like 1.18.12 and the last one 2.2.1 but the same thing.
Hear is video [https://youtu.be/h90deMDvh08](url)

I try with Zip package too
`Downloading packages
arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7
arduino:avrdude@6.3.0-arduino17
arduino:arduinoOTA@1.3.0
arduino:avr@1.8.6
Installing arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7
Configuring tool.
arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 installed
Installing arduino:avrdude@6.3.0-arduino17
Configuring tool.
arduino:avrdude@6.3.0-arduino17 installed
Installing arduino:arduinoOTA@1.3.0
Configuring tool.
arduino:arduinoOTA@1.3.0 installed
Installing platform arduino:avr@1.8.6
Configuring platform.
Platform arduino:avr@1.8.6 installed
Downloading Keyboard@1.0.4
Keyboard@1.0.4
Installing Keyboard@1.0.4
Installed Keyboard@1.0.4
Downloading TFT@1.0.6
TFT@1.0.6
Installing TFT@1.0.6
Installed TFT@1.0.6
Downloading Arduino_BuiltIn@1.0.0
Arduino_BuiltIn@1.0.0
Installing Arduino_BuiltIn@1.0.0
Installed Arduino_BuiltIn@1.0.0
Downloading Firmata@2.5.9
Firmata@2.5.9
Installing Firmata@2.5.9
Installed Firmata@2.5.9
Downloading Mouse@1.0.1
Mouse@1.0.1
Installing Mouse@1.0.1
Installed Mouse@1.0.1
Downloading Stepper@1.1.3
Stepper@1.1.3
Installing Stepper@1.1.3
Installed Stepper@1.1.3
Downloading Ethernet@2.0.2
Ethernet@2.0.2
Installing Ethernet@2.0.2
Installed Ethernet@2.0.2
Downloading LiquidCrystal@1.0.7
LiquidCrystal@1.0.7
Installing LiquidCrystal@1.0.7
Installed LiquidCrystal@1.0.7
Downloading Servo@1.2.1
Servo@1.2.1
Installing Servo@1.2.1
Installed Servo@1.2.1
Downloading SD@1.2.4
SD@1.2.4
Installing SD@1.2.4
Installed SD@1.2.4`

Same Error `In file included from C:\Users\Formingus\Documents\Arduino\libraries\IRremoteESP8266\src/IRac.h:15:0,
                 from C:\Users\Formingus\AppData\Local\Temp\.arduinoIDE-unsaved2023916-16500-fsrplt.v9erg\IRrecvDumpV2\IRrecvDumpV2.ino:33:
C:\Users\Formingus\Documents\Arduino\libraries\IRremoteESP8266\src/ir_Argo.h:14:10: fatal error: set: No such file or directory
 #include <set>
          ^~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1`

**Comment by Formingus** [comment]
[https://youtu.be/gR3XOFoOLfA](url)  Hear is video when failed with last version 2.2.1


While this one from another coder can be compiled WO Problem ``   [https://youtu.be/fN6a06lDx1A](url)

**Comment by SensorsIot** [comment]
This is an old project, and maybe it does no more work.
If you want to try you have to copy the library folder of my Repo (ESP32-IRremote) to the library folder of Arduino. Then it compiles for the ESP32
I just tried it.

**Comment by Formingus** [comment]
> ESP32-IRremote

There is no library folder !! Examples, src, pictures are inside IRemote4.2.0.zip ? If you are talking about this file? If not where to download or advise me, on which project to use for Arduino Nano so i can read remote TV codes? Thanks in advance

**Comment by Formingus** [comment]
![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/a38c88ad-be49-43dd-a60e-f63808728708)

**Comment by SensorsIot** [comment]
Here is the structure inside the zip file: 
![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/13062557/e042356d-1371-4c4e-82a4-f6bbb84074cc)

The ESP32-iRemote folder is a library and theother contains the ino file

**Comment by Formingus** [comment]
![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/cc15f2bb-1766-4e17-a4f4-4d1ba3756bb3)

![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/56abb860-6ce7-4a8e-92bf-b98ee35e6c51)

![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/5f44da7c-bc21-4886-b560-16e1bf3ba401)


Which one to choose ?
![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/d96c3d5e-ae9a-41d9-b4c3-f86aa97fada1)

**Comment by SensorsIot** [comment]
As I wrote before: The ino file is in one folder and the library is in the other. Copy the library to Arduinos library folder and start the ino file. Then it should compile.

**Comment by Formingus** [comment]
> As I wrote before: The ino file is in one folder and the library is in the other. Copy the library to Arduino's library folder and start the ino file. Then it should compile.

Here you dont have INO file !! ARE YOU TALKING ABOUT IRMQQTESP32 FOLDER?
![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/b0b89193-03f8-4b64-9046-8e509aa49b5b)
 Ino Files are inside the example Folder. Can you tell me which one to open ???

![image](https://github.com/SensorsIot/Definitive-Guide-to-IR/assets/37929267/fca0ab91-99fe-400b-965d-f467c4c0b63d)

If you want to help me please be more specific, i am a beginner --- You cant talk with me as advanced, i barely understand.

So, which one to open (NAME), and if this project doesn't work IS THERE SOME OTHER PROJECT THAT CAN RECEIVE REMOTE TV CODRS VIA ARDUINO NANO?? THANKS

**Comment by SensorsIot** [comment]
Yes. You di not need another library. It is in my Github

**Comment by Formingus** [comment]
> Yes. You di not need another library. It is in my Github

Not work

**Comment by medcc-lab** [comment]
Hi,
though the issue is closed, I think the problem reported is what I also experience: When going to the release page, I can't obtain any compiled library, but only a compressed copy of the source code. It does not unpack into a "ESP32-IRremote" folder but into one named like the repo.
I think the release mechanism (build pipeline) is not working as desired.

**Comment by SensorsIot** [comment]
I improved the readme. hope it helps

**Comment by medcc-lab** [comment]
Part of the confusion happened for me since the documentation in the subfolder links to the Releases page which yields a zip that doesn't contain the expected folders. 
The main README.md (your new instructions) don't link there but requests to just download the repo. You may wish to remove the misleading documentation.

**Comment by SensorsIot** [comment]
Updated the `ESP32-IRremote/README.md` - removed the misleading link to the original IRremote releases page and simplified installation instructions.

Hope this works now for you.
