### ISSUE TITLE
irsend keine Reaktion

### ISSUE THREAD

**Issue by malebuffy** [SensorsIot/Definitive-Guide-to-IR#3]
Funktioniert es noch? Habe ein ESP32 Dev Board und benutze für das IR Led, Pin 34 (andere auch versucht). Wenn ich irsend schicke, leuchtet das IR led nicht unter der Handykamera, also keine Reaktion.  Habe dein Code benuzt, ohne den MQTT Teil, also was er als Input bekommt, schickt er wieder raus. Inpout funktioniert, Output nicht. Hast du da eine Idee?

**Comment by malebuffy** [comment]
Ich habe es mit dem Pin 5 versucht, und es funtkioniert. Warum aber Pin 5? ist es ein ESP32 Hardware Thema oder funktioniert deine Version der IRremote Library nur mit Pin 5?

**Comment by SensorsIot** [comment]
Ehrlich gesagt weiss ich es nicht mehr :-(
